# Data sources

## Validity and Reliability of the Data Source

Our project uses the dataset `us_foriegn_aid_complete.csv` obtained from [ForeignAssistance.gov](https://foreignassistance.gov/data), which is the U.S. government’s flagship website that makes the full lifecycle of all US government's foreign assistance data available for public transparency and accountability. The data collection efforts are conducted by the Foreign Assistance Data and Reporting Team from the Department of State and the United States Agency for International Development (FA-DART) and are authorized by the US Office of Management and Budget (OMB). The assistance activities include project, program, cash transfer, delivery of goods, training course, technical assistance, research project, debt relief operation, or a contribution to an international organization, all of which are submitted by respective U.S. government agencies, processed, verified, and combined with the budgetary planning information of the Congress by the reporting team. The data are quarterly uploaded to the website.

## Description of the Dataset

The dataset has 2,897,021 observations and 54 variables. Examples of the variables include `Country ID`, `Income.Group.Name`, `Managing.Agency.Acronym`, `Implementing.Partner.Name`, `International.Category.ID`, `Funding.Agency.Name`, `Foreign.Assistance.Objective.ID`, `Activity.Start.Date`, `Constant.Dollar.Amount`, `year`, etc. Most of the columns are categorical variables that note information about specific entities that participate in the assistance activities, and three numeric columns `year`, `Constant.Dollar.Amount` and `Current.Dollar.Amount` that record the dates and dollar amounts (un)adjusted for inflation of the aid activities.

## Issues with the Dataset

There are a couple of existing problems with the dataset. The first is the immense size of the dataset, so performing exploratory data analysis on it slows computation severely and renders messy and dense visualizations that jeopardize clarity and informativeness for presentation. Second, since the dataset dates back to 1946, there are some discrepancies and inconsistencies due to historical reasons. For example, the U.S. foreign assistance data reported to USAID did not contain activity-level information nor disbursements before 2001. Also, significant lags in reporting are prevalent in assistance activities related to food and military, and thus are often subject to revision. Thus the quality of the data in these areas can hinders our efforts to represent the most accurate picture. Third, we observe that we have only three discrete-valued, numeric variables, two of which represents dollar amounts of aid activities and programs. Thus, it's difficult to use scatterplots to see if there are linear/polynomial/exponential associations between them. Additionally, by examining the dataset, we found that the dataset contains "NULL" data in the `Income.Group.Name`, which is a column that classifies the aid recipient countries by income levels, in accordance with the current World Bank Income Group Country Classification. Based on the criteria of GNI per capita, there are four income groups: low, lower-middle, upper-middle, and high. However, our dataset includes activities of scale of region, such as `Eastern Africa Region`, `Latin America and Caribbean Region`, `Asia Region`, `Sub-Saharan Africa Region`, `World`, etc. These represent activities that affect a collection of countries that fall within the same specified geographical area, and therefore can not be generalized to one "Income Group". So these rows have "NULL" values for `Income.Group.Name` so as not to distort the analysis. The presence of the aforementioned problems prompt us to perform additional data wrangling, transformation and looking at data of our research interests, as described in [Chapter 3](https://theyaoxiao.github.io/US_Foreign_Assistance/data-transformation.html).

