--- 
title: "Visualizing US Foreign Assistance Projects"
author: "Tianmai Jiao, Yao Xiao"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

We are living in an era of rapid socio-economic and political changes, most noted for the isolationist trend spearheaded by the Trump Administration, the spread of the pandemic of the coronavirus, and the new establishment of the fundamentalist Taliban government. The developing world is facing more challenges and threats than ever and the need for aids should only grow stronger. Thus, it is of great interest to investigate the evolution of the US assistance over time, so we can dissect the pattern of the aids provided to different entities and ultimately, motivate leaders and policymakers to make informed decisions regarding the future prospect of foreign assistance. To achieve this goal, we will use a dataset made publicly available that compiles the multi- dimensional information of the foreign assistance portfolio of the US government, spanning from 1946 to 2022 fiscal year. Some of the research questions we intend to explore are listed as follows:

• What categories did the US aids consistently devote the most resources to?

• What countries were the biggest beneficiaries of the US foreign assistance?

• Did the recent growth and development of the private sector investments, NGOs, and other new sectors impact the role of the bilateral and multilateral organizations (e.g. USAID, World Bank, etc.) in providing aids?

• Did the overall time frame of the programs change? What is the trend of foreign assistance towards assistance objective?

• Are there noticeable relationships between the fields,eg:“transaction type name” and “region name”?

• How did the major economic shocks (e.g. subprime mortgage crisis in 2008 and the current pandemic of COVID-19) affect the pattern of the US foreign aids provided to the developing countries?
